### ISSUE TITLE
Add "scripts-to-rule-them-all" for python package

### ISSUE THREAD

**Issue by NGenetzky** [mdklatt/cookiecutter-python-app#10]
What is [scripts-to-rule-them-all](https://github.com/github/scripts-to-rule-them-all)?

> This is a set of boilerplate scripts describing the normalized script pattern that GitHub uses in its projects.

In this case I think it would be sufficient to only implement 'bootstrap' and 'test'.

**Comment by mdklatt** [comment]
The [scripts-to-rule-them-all](https://github.com/github/scripts-to-rule-them-all) project is intriguing, but it doesn't look like it's being developed anymore. The current state only supports Ruby, so it would not be useful here. This template now provides a Makefile to automate some project management tasks, but a more comprehensive (and standard) solution would be nice. There are are a proliferation of Python packaging tools now, but they don't do much for testing or deployment. Add Docker containers to the mix, and the situation gets even worse.  

[Tox](https://tox.wiki/en/latest/index.html) is a promising, albeit heavyweight, solution for this. This template tries not to be *too* opinionated while focusing on the basics common to any project, so automation/CI/deployment is left to the user for now.

[Obligatory XKCD](https://xkcd.com/927/).
